# Generated by Django 4.2.18 on 2025-04-25 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Промокод')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Начала действия')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец действия купона')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('active', models.BooleanField(default=True)),
                ('usage', models.IntegerField(default=0)),
                ('max_usage', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
